# Generated by Django 4.1.4 on 2023-11-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_remove_application_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='age',
            field=models.IntegerField(default=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='phone',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
